name: Build Container
jobs:
  build:
    runs-on: ubuntu-24.04 # uses podman from 24.04 or later
    env:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/${{ github.repository_owner }}/TARGET_CONTAINER
    steps:
      - env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: printenv PASSWORD | podman login -v ${{ env.REGISTRY }} -u "$USERNAME" --password-stdin

      - uses: actions/checkout@v4

      - run: podman build -t ${{ env.IMAGE }} .

      - run: podman push ${{ env.IMAGE }}
      # - run: podman image inspect --format '{{ range .RepoTags }}{{ . }} {{ end }}'
      #     ${{ env.IMAGE }} | xargs -n 1 podman push

      - if: ${{ !cancelled() }} # runs even if previous steps failed
        run: podman logout ${{ env.REGISTRY }}
