name: Build Container
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/${{ github.repository_owner }}/TARGET_CONTAINER
      CACHE_REPO: ghcr.io/${{ github.repository_owner }}/0__buildcache__TARGET_CONTAINER
    steps:
      - env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: printenv PASSWORD | podman login -v ${{ env.REGISTRY }} -u "$USERNAME" --password-stdin

      - uses: actions/checkout@v4

      # TODO: switch to --pull=newer once supported https://github.com/containers/podman/issues/22845
      - run: podman build --pull=always --cache-from ${{ env.CACHE_REPO }} --cache-to ${{ env.CACHE_REPO }} -t ${{ env.IMAGE }} .

      - run: podman image inspect --format '{{ range .RepoTags }}{{ . }} {{ end }}'
          ${{ env.IMAGE }} | xargs -n 1 podman push

      - if: ${{ !cancelled() }} # runs even if previous steps failed
        run: podman logout ${{ env.REGISTRY }}
